import 'package:uuid/uuid.dart';
import 'package:json_annotation/json_annotation.dart';
import 'address.dart';
import 'post.dart';
import 'profile.dart';

part 'user.g.dart';

@JsonSerializable(explicitToJson: true)
class User {
  final String id;

  /// Rename JSON key: API sends "full_name", Dart field is "name"
  /// @JsonKey(name: 'full_name')
  /// final String name;
  final String name;

  /// Default if missing: if API lacks "email" key, use default value
  /// @JsonKey(defaultValue: 'no-email@example.com')
  /// final String email;
  ///
  /// Ignore field: don't serialize/deserialize this field
  /// @JsonKey(ignore: true)
  /// final String? tempData;
  final String email;

  final Profile profile;
  final List<Post> posts;

  Address? address; // Nested object example

  User({
    required this.name,
    required this.email,
    required this.profile,
    required this.posts,
    this.address,
  }) : id = const Uuid().v4();

  Map<String, dynamic> toMap() {
    return {'id': id, 'name': name, 'email': email};
  }

  // manual fromJson factory
  // factory User.fromJson(Map<String, dynamic> json) {
  //   return User(name: json['name'] as String, email: json['email'] as String);
  // }

  /// Generated by build_runner. Calls _$UserFromJson() helper.
  /// build_runner generates implementation like:
  /// ```
  /// factory User.fromJson(Map<String, dynamic> json) {
  ///   return User(
  ///     id: json['id'] as String,
  ///     name: json['full_name'] as String,  // Renamed!
  ///     email: json['email'] as String? ?? 'no-email@example.com',  // Default!
  ///   );
  /// }
  /// ```
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  /// Generated by build_runner. Calls _$UserToJson() helper.
  /// build_runner generates implementation like:
  /// ```
  /// Map<String, dynamic> toJson() {
  ///   return {
  ///     'id': id,
  ///     'full_name': name,  // Renamed!
  ///     'email': email,
  ///   };
  /// }
  /// ```
  Map<String, dynamic> toJson() => _$UserToJson(this);

  @override
  String toString() => 'User(id: $id, name: $name, email: $email)';
}
